SELECT YEAR, (m.SIZE - e.SIZE_OF_COLONY) YEAR_DEV, ID
FROM
    ECOLI_DATA e JOIN
    (
        SELECT
            YEAR(DIFFERENTIATION_DATE) AS YEAR,
            MAX(SIZE_OF_COLONY) AS SIZE
        FROM ECOLI_DATA
        GROUP BY YEAR
    ) m
    ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY
    YEAR ASC, YEAR_DEV ASC