WITH MAX_PRICES AS (
    SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM
    FOOD_PRODUCT
WHERE
    (CATEGORY, PRICE) IN (SELECT CATEGORY, PRICE FROM MAX_PRICES)
  AND
    CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC