SELECT
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM(bs.SALES * b.PRICE) AS TOTAL_SALES
FROM
    BOOK b
        JOIN AUTHOR a
             ON b.AUTHOR_ID = a.AUTHOR_ID
        JOIN BOOK_SALES bs
             ON b.BOOK_ID = bs.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY
    a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY
    a.AUTHOR_ID ASC, b.CATEGORY DESC