WITH CAR_RENTAL_AT AS (
    SELECT SUM('2022-10-16' BETWEEN START_DATE AND END_DATE) AS RENTABLE, CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
)

SELECT CAR_ID, IF(RENTABLE < 1, '대여 가능', '대여중') AS AVAILABILITY
FROM CAR_RENTAL_AT
ORDER BY CAR_ID DESC